
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://tpjaxws.sid.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertEuroToDH", targetNamespace = "http://tpjaxws.sid.org/", className = "proxy.ConvertEuroToDH")
    @ResponseWrapper(localName = "convertEuroToDHResponse", targetNamespace = "http://tpjaxws.sid.org/", className = "proxy.ConvertEuroToDHResponse")
    @Action(input = "http://tpjaxws.sid.org/BankService/convertEuroToDHRequest", output = "http://tpjaxws.sid.org/BankService/convertEuroToDHResponse")
    public double convertEuroToDH(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://tpjaxws.sid.org/", className = "proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://tpjaxws.sid.org/", className = "proxy.GetAccountResponse")
    @Action(input = "http://tpjaxws.sid.org/BankService/getAccountRequest", output = "http://tpjaxws.sid.org/BankService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAccounts", targetNamespace = "http://tpjaxws.sid.org/", className = "proxy.ListAccounts")
    @ResponseWrapper(localName = "listAccountsResponse", targetNamespace = "http://tpjaxws.sid.org/", className = "proxy.ListAccountsResponse")
    @Action(input = "http://tpjaxws.sid.org/BankService/listAccountsRequest", output = "http://tpjaxws.sid.org/BankService/listAccountsResponse")
    public List<Account> listAccounts();

}
